In [2]:
import numpy as np



In [3]:
a=np.array([1,2,3,4,5])
a



array([1, 2, 3, 4, 5])

In [4]:
import matplotlib as plt

In [5]:
y_pred=[2,4,6]
y_actual=[1,3,5]
mean=np.mean(np.square(np.subtract(y_pred,y_actual)))
mean

1.0

In [6]:
arr=np.arange(0,12)
arr.shape

(12,)

In [7]:
arr=np.arange(0,12)
arr.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
data=np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [16]:
data.max()
data
data.min()
data
data.sum()
data

array([1., 1., 1., 1., 1., 1.])

In [14]:
data=np.ones(6)
data
data1=np.zeros((3,4))
data1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
x=np.array([[1,2],[3,4],[5,6]])
y=x.max(axis=1)
y


array([2, 4, 6])

In [76]:
n=np.arange(0,8)
m=np.arange(8,17)
x=np.mean(n)
x1=np.sum(np.square(np.subtract(x,n)))/len(n)
y=np.mean(m)
y2=np.sum(np.square(np.subtract(y,m)))/len(m)

z=(x1+y2)/2
z





5.958333333333334